manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: joelspadin
      revision: send-string-behavior
      import: app/west.yml
  self:
    path: config
